title: Jan Emrich
logo: /assets/img/profil.png
description: Everything Data and Machine Learning. I like to anayze, visualize and build models of data. Both classical statistics and deep learning.
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: G-H884S5WRT5