title: Jan Emrich
logo: /assets/img/profil.png
description: "Tech Stack: Python, PyTorch, Numpy, Keras, SciPy, Pandas, C++, Docker, Linux, Slurm, REST, Microservices, SQL"
show_downloads: false
theme: jekyll-theme-minimal
google_analytics: G-H884S5WRT5